{{- if .Values.modelsPvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "roboqc-testbed.fullname" . }}-models
  labels:
    {{- include "roboqc-testbed.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.modelsPvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.modelsPvc.size }}
  storageClassName: {{ .Values.modelsPvc.storageClass }}
{{- end }}
