{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "roboqc-testbed.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    {{- include "roboqc-testbed.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "roboqc-testbed.name" . }}
  namespaceSelector:
    matchNames: ["{{ .Release.Namespace }}"]
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}
