"""Render deploy templates into runtime config files.

The YAML files under :mod:`roboqc_data.deploy` are reviewable
manifests, not the formats DeepStream / Triton actually load. This
module renders them:

- DeepStream template → a flat ``deepstream_app_config.txt`` in the
  INI-style DeepStream expects, plus one ``roiN.txt`` per camera ROI.
- Triton template → one ``config.pbtxt`` per model in the standard
  Triton model-repository layout.

The renderers are intentionally plain string builders — no jinja, no
protobuf lib — because the target formats are simple and we want the
output diff-reviewable. Validation of the *input* template happens at
load time via :func:`load_template`.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from ..schema.taxonomy import DefectClass


def load_template(path: Path) -> dict[str, Any]:
    """Load and lightly validate a deploy template.

    Raises:
        ValueError: if the YAML is empty or missing the ``application``
            block every template must carry.
    """
    data = yaml.safe_load(path.read_text())
    if not isinstance(data, dict) or "application" not in data:
        raise ValueError(f"{path} is not a valid deploy template (missing 'application')")
    return data


def render_deepstream(template: dict[str, Any], out_dir: Path) -> list[Path]:
    """Render a DeepStream template into config files.

    Returns the list of written paths: the main app config plus one
    ROI file per region_of_interest.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    app = template["application"]
    written: list[Path] = []

    lines: list[str] = [
        "# Generated by roboqc_data.deploy.render — do not edit by hand.",
        "[application]",
        f"station-id={app['station_id']}",
        "",
    ]
    for idx, source in enumerate(template.get("sources", [])):
        lines += [
            f"[source{idx}]",
            "enable=1",
            f"uri={source['uri']}",
            f"width={source.get('width', 1920)}",
            f"height={source.get('height', 1080)}",
            "",
        ]
    inference = template.get("inference", {})
    for role in ("primary", "secondary"):
        cfg = inference.get(role)
        if cfg is None:
            continue
        lines += [
            f"[inference-{role}]",
            f"engine={cfg['engine']}",
            f"precision={cfg.get('precision', 'fp16')}",
            f"threshold={cfg.get('threshold', 0.5)}",
            "",
        ]
    sink = template.get("sink", {})
    if sink:
        lines += [
            "[sink]",
            f"type={sink.get('type', 'rest')}",
            f"endpoint={sink.get('endpoint', '')}",
            f"hitl-confidence-threshold={sink.get('hitl_confidence_threshold', 0.85)}",
            "",
        ]

    app_config = out_dir / "deepstream_app_config.txt"
    app_config.write_text("\n".join(lines), encoding="utf-8")
    written.append(app_config)

    for roi in template.get("regions_of_interest", []):
        # Validate every ROI class against the canonical taxonomy.
        for cls_name in roi.get("classes", []):
            DefectClass(cls_name)
        roi_path = out_dir / f"roi_{roi['name']}.txt"
        roi_lines = [
            f"# ROI: {roi['name']} (source={roi['source_id']})",
            "polygon=" + ";".join(f"{x:.4f},{y:.4f}" for x, y in roi["polygon"]),
            "classes=" + ",".join(roi["classes"]),
        ]
        roi_path.write_text("\n".join(roi_lines) + "\n", encoding="utf-8")
        written.append(roi_path)

    return written


def render_triton(template: dict[str, Any], out_dir: Path) -> list[Path]:
    """Render a Triton template into one config.pbtxt per model.

    Output layout matches Triton's model repository:
    ``<out_dir>/<model_name>/config.pbtxt``.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    for model in template.get("models", []):
        model_dir = out_dir / model["name"]
        model_dir.mkdir(parents=True, exist_ok=True)
        lines = [
            "# Generated by roboqc_data.deploy.render — do not edit by hand.",
            f'name: "{model["name"]}"',
            f'platform: "{model["platform"]}"',
            f"max_batch_size: {model.get('max_batch_size', 1)}",
        ]
        for io_key, io_label in (("input", "input"), ("output", "output")):
            for io in model.get(io_key, []):
                dims = ", ".join(str(d) for d in io["dims"])
                lines += [
                    f"{io_label} [",
                    f'  {{ name: "{io["name"]}" data_type: TYPE_{io["data_type"]} dims: [ {dims} ] }}',
                    "]",
                ]
        for group in model.get("instance_group", []):
            lines += [
                "instance_group [",
                f"  {{ kind: {group['kind']} count: {group.get('count', 1)} }}",
                "]",
            ]
        config_path = model_dir / "config.pbtxt"
        config_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        written.append(config_path)

    return written


def render(template_path: Path, out_dir: Path) -> list[Path]:
    """Render any deploy template, dispatching on its shape.

    A template with a ``models`` list is Triton; one with ``sources``
    is DeepStream.
    """
    template = load_template(template_path)
    if "models" in template:
        return render_triton(template, out_dir)
    if "sources" in template:
        return render_deepstream(template, out_dir)
    raise ValueError(f"{template_path}: cannot tell DeepStream from Triton (no 'sources'/'models')")
