"""Tests for iteration-10: deploy template rendering.

- render_deepstream → app config + per-ROI files
- render_triton → one config.pbtxt per model
- render() dispatch + load_template validation
- CLI deploy-render command
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

from roboqc_data.cli.main import app
from roboqc_data.deploy.render import (
    load_template,
    render,
    render_deepstream,
    render_triton,
)

runner = CliRunner()

DEPLOY_DIR = Path(__file__).resolve().parents[1] / "src" / "roboqc_data" / "deploy"
DEEPSTREAM_TEMPLATE = DEPLOY_DIR / "deepstream_inspection_cell.yaml"
TRITON_TEMPLATE = DEPLOY_DIR / "triton_inference_server.yaml"


def test_load_template_rejects_non_template(tmp_path):
    bad = tmp_path / "bad.yaml"
    bad.write_text("just: a map\n")
    with pytest.raises(ValueError, match="not a valid deploy template"):
        load_template(bad)


def test_render_deepstream_writes_app_config_and_roi_files(tmp_path):
    template = load_template(DEEPSTREAM_TEMPLATE)
    out = tmp_path / "ds"
    written = render_deepstream(template, out)

    app_config = out / "deepstream_app_config.txt"
    assert app_config in written
    text = app_config.read_text()
    assert "[application]" in text
    assert "station-id=" in text
    assert "[source0]" in text and "[source1]" in text
    assert "[inference-primary]" in text

    roi_files = [p for p in written if p.name.startswith("roi_")]
    assert len(roi_files) == 2
    for roi in roi_files:
        body = roi.read_text()
        assert body.startswith("# ROI:")
        assert "polygon=" in body
        assert "classes=" in body


def test_render_triton_writes_one_config_per_model(tmp_path):
    template = load_template(TRITON_TEMPLATE)
    out = tmp_path / "triton"
    written = render_triton(template, out)

    assert len(written) == 3
    names = {p.parent.name for p in written}
    assert names == {"yolo26-seg", "patchcore_lite", "velm_orchestrator"}
    for path in written:
        assert path.name == "config.pbtxt"
        text = path.read_text()
        assert text.startswith("# Generated by roboqc_data.deploy.render")
        assert "platform:" in text
        assert "max_batch_size:" in text


def test_render_dispatches_deepstream_vs_triton(tmp_path):
    ds_out = tmp_path / "ds"
    triton_out = tmp_path / "triton"
    ds_written = render(DEEPSTREAM_TEMPLATE, ds_out)
    triton_written = render(TRITON_TEMPLATE, triton_out)
    # DeepStream → flat .txt files; Triton → config.pbtxt files.
    assert all(p.suffix == ".txt" for p in ds_written)
    assert all(p.name == "config.pbtxt" for p in triton_written)


def test_render_rejects_ambiguous_template(tmp_path):
    ambiguous = tmp_path / "weird.yaml"
    ambiguous.write_text("application:\n  station_id: X\n")
    with pytest.raises(ValueError, match="cannot tell DeepStream from Triton"):
        render(ambiguous, tmp_path / "out")


def test_cli_deploy_render_deepstream(tmp_path):
    out = tmp_path / "rendered"
    result = runner.invoke(
        app,
        ["deploy-render", "--template", str(DEEPSTREAM_TEMPLATE), "--out", str(out)],
    )
    assert result.exit_code == 0, result.output
    payload = json.loads(result.output.strip().splitlines()[-1])
    assert payload["template"].endswith("deepstream_inspection_cell.yaml")
    assert len(payload["files"]) >= 3  # app config + 2 ROI files
    assert (out / "deepstream_app_config.txt").is_file()


def test_cli_deploy_render_triton(tmp_path):
    out = tmp_path / "rendered"
    result = runner.invoke(
        app,
        ["deploy-render", "--template", str(TRITON_TEMPLATE), "--out", str(out)],
    )
    assert result.exit_code == 0, result.output
    payload = json.loads(result.output.strip().splitlines()[-1])
    assert len(payload["files"]) == 3
    assert (out / "yolo26-seg" / "config.pbtxt").is_file()
